default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: Welcome@123

development:
  <<: *default
  database: twilio_dev


production:
  <<: *default
  database: twilio_production
